# Generated by Django 5.1 on 2024-10-06 12:11

import booking.models.media
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='ExactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда')),
                ('apartment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=booking.models.media.object_directory_path, verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок картинки')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
            },
        ),
        migrations.CreateModel(
            name='ObjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок видео')),
            ],
            options={
                'verbose_name': 'Видео объекта',
                'verbose_name_plural': 'Видео объектов',
            },
        ),
        migrations.CreateModel(
            name='PriceListOfRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='Начало срока')),
                ('last_day', models.DateField(verbose_name='Конец срока')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('Square', models.PositiveSmallIntegerField(verbose_name='Площадь')),
                ('adult', models.PositiveSmallIntegerField(verbose_name='Количество взрослых')),
                ('Kid', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('sleeping_places', models.PositiveSmallIntegerField(verbose_name='Количество спальных мест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Номер скрыт')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='TypeOfObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('is_independent', models.BooleanField(verbose_name='Объект независимый')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объекта',
            },
        ),
        migrations.CreateModel(
            name='IndependentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('Square', models.PositiveSmallIntegerField(verbose_name='Площадь')),
                ('adult', models.PositiveSmallIntegerField(verbose_name='Количество взрослых')),
                ('Kid', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('sleeping_places', models.PositiveSmallIntegerField(verbose_name='Количество спальных мест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('exact_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent', to='booking.exactaddress', verbose_name='Точный адрес')),
            ],
            options={
                'verbose_name': 'Самостоятельный объект',
                'verbose_name_plural': 'Самостоятельные объекты',
            },
        ),
        migrations.CreateModel(
            name='IndependentPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='Начало срока')),
                ('last_day', models.DateField(verbose_name='Конец срока')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='booking.independentobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Прайс лист самостоятельного объекта',
                'verbose_name_plural': 'Прайс листы самостоятельного объекта',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название объекта')),
                ('is_active', models.BooleanField(default=False, verbose_name='Объявление активно')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number_of_flat', models.PositiveSmallIntegerField(verbose_name='Количество этажей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Объявление скрыто')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object_by_address', to='booking.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
