# Generated by Django 5.1 on 2024-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exactaddress',
            options={'verbose_name': 'Точный адрес', 'verbose_name_plural': 'Точные адреса'},
        ),
        migrations.AlterModelOptions(
            name='pricelistofroom',
            options={'verbose_name': 'Прайс лист номера', 'verbose_name_plural': 'Прайс листы номеров'},
        ),
        migrations.AddField(
            model_name='address',
            name='sea_distance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Расстояние до моря'),
            preserve_default=False,
        ),
    ]
