# Generated by Django 5.1 on 2024-10-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_city_alter_address_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='city',
            name='sea_latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=6, verbose_name='Широта пляжа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='sea_longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=6, verbose_name='Долгота пляжа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Широта'),
        ),
    ]
