# Generated by Django 5.1 on 2024-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_city_options_city_sea_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sea_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта пляжа'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sea_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота пляжа'),
        ),
    ]
