# Generated by Django 5.1 on 2024-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='independentobject',
            old_name='Kid',
            new_name='kid',
        ),
        migrations.RenameField(
            model_name='independentobject',
            old_name='Square',
            new_name='square',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Kid',
            new_name='kid',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Square',
            new_name='square',
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота'),
        ),
    ]
