# Generated by Django 5.1 on 2024-10-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_kid_independentobject_kid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectimage',
            old_name='image',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='objectvideo',
            old_name='video_url',
            new_name='media',
        ),
    ]
