# Generated by Django 5.1 on 2024-09-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
    ]
